# Generated by Django 4.1.2 on 2022-10-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="processor",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="ram",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="screen",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="storage",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="system",
            old_name="_id",
            new_name="id",
        ),
    ]
