# Generated by Django 4.1.2 on 2022-10-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_r_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='r_updated',
        ),
    ]
