# Generated by Django 4.1.2 on 2022-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
