# Generated by Django 4.1.2 on 2022-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_updated_product_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.CharField(max_length=7),
        ),
    ]
