# Generated by Django 4.1.2 on 2022-10-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protype",
            fields=[
                (
                    "_id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="processors",
            name="type",
        ),
        migrations.AddField(
            model_name="products",
            name="protype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.protype",
                verbose_name="Protype",
            ),
        ),
    ]
