# Generated by Django 4.1.2 on 2022-10-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0003_hepsiburada_n11_trendyol_vatan_remove_products_sites_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
