# Generated by Django 4.1.2 on 2022-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0004_rename_products_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="protype",
        ),
        migrations.AddField(
            model_name="processors",
            name="type",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Protype",
        ),
    ]
