# Generated by Django 4.1.2 on 2022-10-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0006_sitesinformations_remove_processors_gen_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Processors",
            new_name="Processor",
        ),
        migrations.RenameModel(
            old_name="Storages",
            new_name="Ram",
        ),
        migrations.RenameModel(
            old_name="Systems",
            new_name="Screen",
        ),
        migrations.RenameModel(
            old_name="SitesInformations",
            new_name="SitesInformation",
        ),
        migrations.RenameModel(
            old_name="Rams",
            new_name="Storage",
        ),
        migrations.RenameModel(
            old_name="Screens",
            new_name="System",
        ),
    ]
