# Generated by Django 4.1.2 on 2022-10-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0007_rename_processors_processor_rename_storages_ram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ram",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.ram",
                verbose_name="Ram",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.screen",
                verbose_name="Screen",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="sites",
        ),
        migrations.AlterField(
            model_name="product",
            name="storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.storage",
                verbose_name="Storage",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.system",
                verbose_name="System",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sites",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scrap.sitesinformation",
                verbose_name="SitesInformation",
            ),
        ),
    ]
