# Generated by Django 4.1.2 on 2022-10-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0009_remove_product_sites_sitesinformation_whichproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
