# Generated by Django 4.1.2 on 2022-10-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0010_alter_product_slug_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesinformation",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
