# Generated by Django 4.1.2 on 2022-10-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0011_alter_sitesinformation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesinformation",
            name="name",
        ),
    ]
