# Generated by Django 4.1.2 on 2022-10-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0012_remove_sitesinformation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesinformation",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sitesinformation",
            name="rate",
            field=models.IntegerField(default=0),
        ),
    ]
