# Generated by Django 4.1.2 on 2022-10-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0015_brands_alter_product_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
