# Generated by Django 4.1.2 on 2022-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0016_rename_title_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesinformation",
            name="sitename",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
