# Generated by Django 4.1.2 on 2022-10-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0018_product_sitelink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sitelink",
            new_name="image",
        ),
    ]
