# Generated by Django 4.1.2 on 2022-10-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0021_rename__id_brand_id_rename__id_processor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.brand', verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.processor', verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.ram', verbose_name='Ram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.screen', verbose_name='Screen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.storage', verbose_name='Storage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='sitesinformation',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sitesinformation',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sitesinformation',
            name='sitename',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesinformation',
            name='whichproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.product', verbose_name='Laptop'),
        ),
    ]
